export const navigation = [
  ['introduction', 'Introduction'],
  ['quantum-threat', 'Quantum Threat'],
  ['ml-kem', 'ML-KEM Lab'],
  ['secure-message', 'Secure Message'],
  ['ml-dsa', 'ML-DSA Lab'],
  ['slh-dsa', 'SLH-DSA Lab'],
  ['comparison', 'Algorithm Comparison'],
  ['lattice', 'Lattice Explainer'],
  ['classical', 'Classical vs PQC'],
  ['uses', 'Real-World Uses'],
  ['migration', 'Migration Simulator'],
  ['myths', 'PQC Myths'],
  ['glossary', 'Glossary'],
  ['about', 'About / References'],
];
export const glossary: Record<string, string> = {
  Cryptography:
    'Mathematical techniques for protecting information and verifying its integrity and origin.',
  Plaintext: 'The original readable data before encryption.',
  Ciphertext:
    'Data produced by encryption. A KEM ciphertext instead carries an encapsulated secret, not the application’s message.',
  'Public key':
    'The shareable half of an asymmetric key pair. Its connection to an identity must still be authenticated.',
  'Private key':
    'The secret half of a key pair, used to decapsulate or sign. Also called a secret key.',
  'Shared secret':
    'Secret key material available to both participants after successful key establishment.',
  'Symmetric encryption':
    'Encryption in which both sides use the same secret key, as with AES.',
  'Asymmetric cryptography':
    'Cryptography using related public and private keys for roles such as key establishment and signatures.',
  'Key encapsulation mechanism':
    'A public-key mechanism that creates a shared secret and a ciphertext from which the private-key holder recovers that secret.',
  'Digital signature':
    'A value created using a private key that a public key can verify against an exact message.',
  'Hash function':
    'A function mapping arbitrary input to a fixed-size digest. Cryptographic hashes resist finding collisions and reversing the digest.',
  Lattice:
    'A repeating arrangement of points generated by integer combinations of basis vectors; cryptographic constructions use high-dimensional algebra.',
  'Post-quantum cryptography':
    'Conventional-computer algorithms designed to resist both classical and quantum attacks.',
  'Quantum cryptography':
    'Cryptographic techniques relying on quantum physical phenomena, rather than only conventional computation.',
  'Quantum key distribution':
    'A physical method of distributing key material using quantum states. It requires specialized equipment and an authenticated classical channel.',
  'Cryptographic agility':
    'The ability to inventory, replace, configure, and update cryptographic algorithms and protocols without rebuilding an entire system.',
  'Harvest now, decrypt later':
    'Collecting encrypted traffic now with the intention of decrypting it later as attack capabilities improve.',
};
export const myths = [
  [
    'You need a quantum computer to use post-quantum cryptography.',
    'False. PQC algorithms run on conventional computers. You are running them in this browser.',
  ],
  [
    'ML-KEM encrypts all of your data.',
    'Not normally. ML-KEM establishes a shared secret that is typically used with symmetric encryption. AES-GCM handles the application data in this playground.',
  ],
  [
    'AES becomes useless once quantum computers exist.',
    'False. Symmetric cryptography is affected differently from RSA and elliptic-curve public-key cryptography. Grover’s algorithm offers a generic quadratic search speedup in an idealized model, rather than Shor’s attack on factoring and discrete logarithms.',
  ],
  [
    'Post-quantum cryptography and quantum key distribution are the same thing.',
    'False. PQC uses conventional computing and new algorithms. QKD uses quantum physical systems and specialized hardware.',
  ],
  [
    'We should simply wait until powerful quantum computers exist before migrating.',
    'Migration can take years: inventories, certificates, protocols, hardware, embedded systems, procurement, and interoperability all need attention. Long-lived secrets may already face harvest-now-decrypt-later exposure.',
  ],
];
export const uses = [
  [
    'TLS / HTTPS',
    'Browsers and servers establish encryption keys before exchanging protected data. Migration concerns both the key exchange and the signatures that authenticate the connection.',
  ],
  [
    'VPNs',
    'VPN systems depend on key establishment and authentication. Upgrading one end is insufficient: peers, protocols, and management tools must interoperate.',
  ],
  [
    'Software Signing',
    'Vendors sign updates so recipients can verify origin and integrity. Larger PQC signatures affect distribution formats and the verifiers installed on older devices.',
  ],
  [
    'Secure Boot',
    'Devices verify signed firmware before executing it. Trust anchors built into hardware may be difficult to replace, making early lifecycle planning important.',
  ],
  [
    'Embedded Systems',
    'Vehicles, industrial equipment, defense systems, and infrastructure can remain deployed for decades. Limited memory, bandwidth, and update access complicate migration.',
  ],
  [
    'PKI and Certificates',
    'Certificate authorities and enterprise PKI need quantum-resistant signature strategies and compatible protocols for key establishment. Certificate chains, issuance tools, and relying parties must evolve together.',
  ],
];
export const references = [
  [
    'NIST FIPS 203 — ML-KEM',
    'https://csrc.nist.gov/pubs/fips/203/final',
    'The finalized module-lattice key-encapsulation standard.',
  ],
  [
    'NIST FIPS 204 — ML-DSA',
    'https://csrc.nist.gov/pubs/fips/204/final',
    'The finalized module-lattice digital-signature standard.',
  ],
  [
    'NIST FIPS 205 — SLH-DSA',
    'https://csrc.nist.gov/pubs/fips/205/final',
    'The finalized stateless hash-based digital-signature standard.',
  ],
  [
    'NIST Post-Quantum Cryptography project',
    'https://csrc.nist.gov/projects/post-quantum-cryptography',
    'Standards, project updates, and the broader standardization effort.',
  ],
  [
    'NIST migration project',
    'https://www.nccoe.nist.gov/applied-cryptography/migration-to-pqc',
    'Migration guidance, discovery, and interoperability work.',
  ],
  [
    'noble-post-quantum documentation',
    'https://github.com/paulmillr/noble-post-quantum/tree/0.7.1',
    'The MIT-licensed third-party implementation used here. Standards implementation is not the same as FIPS module validation.',
  ],
];
export const slug = (text: string) => text.toLowerCase().replaceAll(' ', '-');
